name: Update Gist

on:
  workflow_dispatch:
    inputs:
      trigger_source:
        description: "Who triggered this workflow"
        required: false
        default: "manual"
        
  schedule:
    # GitHub Actions cron uses UTC. 13:20 UTC = 20:20 Asia/Bangkok.
    - cron: '30 14 * * *'


jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Show trigger source
        run: echo "Triggered from: ${{ github.event.inputs.trigger_source }}"
        
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install packages
        run: pip install requests

      - name: Run updater
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_OLD: ${{ secrets.GIST_OLD }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python scripts/update_gist.py
